# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: probe_dock_rspec 0.4.1 ruby lib

Gem::Specification.new do |s|
  s.name = "probe_dock_rspec"
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Simon Oulevay (Alpha Hydrae)"]
  s.date = "2015-02-10"
  s.email = "simon.oulevay@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "lib/probe_dock_rspec.rb",
    "lib/probe_dock_rspec/cache.rb",
    "lib/probe_dock_rspec/client.rb",
    "lib/probe_dock_rspec/config.rb",
    "lib/probe_dock_rspec/formatter.rb",
    "lib/probe_dock_rspec/project.rb",
    "lib/probe_dock_rspec/server.rb",
    "lib/probe_dock_rspec/tasks.rb",
    "lib/probe_dock_rspec/test_payload.rb",
    "lib/probe_dock_rspec/test_result.rb",
    "lib/probe_dock_rspec/test_run.rb",
    "lib/probe_dock_rspec/uid.rb"
  ]
  s.homepage = "https://github.com/probe-dock/probe-dock-rspec"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "RSpec probe to send test results to Probe Dock."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, ["~> 3.1"])
      s.add_runtime_dependency(%q<oj>, ["~> 2.1"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.13"])
      s.add_runtime_dependency(%q<paint>, ["~> 0.8"])
      s.add_runtime_dependency(%q<rake>, ["~> 10.1"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake-version>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<fakefs>, [">= 0"])
      s.add_development_dependency(%q<rspec-its>, [">= 0"])
      s.add_development_dependency(%q<rspec-collection_matchers>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 3.1"])
      s.add_dependency(%q<oj>, ["~> 2.1"])
      s.add_dependency(%q<httparty>, ["~> 0.13"])
      s.add_dependency(%q<paint>, ["~> 0.8"])
      s.add_dependency(%q<rake>, ["~> 10.1"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake-version>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<fakefs>, [">= 0"])
      s.add_dependency(%q<rspec-its>, [">= 0"])
      s.add_dependency(%q<rspec-collection_matchers>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 3.1"])
    s.add_dependency(%q<oj>, ["~> 2.1"])
    s.add_dependency(%q<httparty>, ["~> 0.13"])
    s.add_dependency(%q<paint>, ["~> 0.8"])
    s.add_dependency(%q<rake>, ["~> 10.1"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake-version>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<fakefs>, [">= 0"])
    s.add_dependency(%q<rspec-its>, [">= 0"])
    s.add_dependency(%q<rspec-collection_matchers>, [">= 0"])
  end
end

